### PR TITLE
Added Database UML and SQL

### PR DESCRIPTION
**Pull request by lunitin**
Created initial DB schema in MySQL workbench and exported pdf and sql versions.

### CODE REVIEW

**Comment by dswan1992** [comment]
Everything looks good to me, I'll wait on the others to look it over

**Comment by bonnerke** [comment]
The relationships also seem good to me, eventually we have to associate the rewards and categories, but everything is in place

**Comment by lunitin** [comment]
Re: Rewards. I was thinking that table would just be the scale of rewards, the level and the required number of seconds for that level. 

However,  maybe there is no need for an xp table at all. What if we just used a simple algorithm like 10k seconds per level? or base 10k and double every level ?

**Comment by bonnerke** [comment]
I like your idea for the levels in terms of a simple function of time. That makes things simple and easy to keep track of.

It would be rewarding if those levels would correlate with some sort of value, sort of like how it's said that you need 10,000 hours to become a "master" in a subject, but I can't quite think of an equivalent idea for tasks which task a fraction of that, since 9 years seems a bit long.

**Comment by jordanpemberton** [comment]
These look good to me!

**Comment by dkeech** [comment]
Looks good to me

**Pull request merged**
